### ISSUE TITLE
Mensajes de error al llenar formulario

### ISSUE THREAD

**Issue by heidygerbi** [claudiamalasquezaq/LIM008-social-network#1]
Los mensajes de error se quedan con el primer error recibido y no se actualizan cuando el usuario genera un nuevo error.
![image](https://user-images.githubusercontent.com/25209833/51881309-a8e97380-2348-11e9-9c2d-db8d1a526f2e.png)

en el caso de un nuevo error debe actualizar el tipo de error.
(tal vez utilizando warning-em.innerHTML=''; en cada condicional)

**Comment by claudiamalasquezaq** [comment]
Te refieres a los <p> de warning, cierto? Hay que volver a evaluar las condicionales
