### ISSUE TITLE
HU03: Crear un post

### ISSUE THREAD

**Issue by claudiamalasquezaq** [claudiamalasquezaq/LIM008-social-network#7]
- [x] Crear función en firebase-controller para crear post.
- [x] Implementar la función crear en la intefaz de usuario (IU).
- [x] Validar que el text area no esté vacío.
- [x] Diseño del text area donde se escribirá el post.
- [x] Implementar test para la función crear post.

**Comment by heidygerbi** [comment]
Cambios correctos
